# 指定端口
server:
  port: 8886

# spring-cloud配置
spring:
  application:
    # 服务名称
    name: springcloud-gateway

  # 开启服务发现注册发现
  # 并且spring cloud gateway自动根据服务发现为每一个服务创建了一个router
  # 这个router将以服务名开头的请求路径转发到对应的服务
  # gateway自带负载均衡
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          # 将请求路径上的服务名配置为小写（因为服务注册的时候，向注册中心注册时将服务名转成大写的了）
          # 这样的话就可以访问127.0.0.1:8886/另一个服务提供者的服务名/方法负载访问了
          lowerCaseServiceId: true

      # 路由可以通过配置文件添加，这里的路由是为了别的服务名重命名（重新调整路劲）（如果不加这个的话访问将是一大串路劲）
      # 加上这个的话需要把上面的enable改为false，不然的话springcloud-eureka-client每个方法都会创建两个路由
      routes:
        - id: clientRout
          uri: lb://springcloud-eureka-client
          predicates:
            - Path=/client/*
          filters:
            - StripPrefix=1



