# 指定端口
server:
  port: 8884

# spring-cloud配置
spring:
  application:
    # 服务名称
    name: springcloud-feign

  # 服务链路追踪
  zipkin:
    # zipkin默认端口
    base-url: http://localhost:9411
    enabled: true

  #服务跟踪消息收集率，1代表每一条都收集，0.1代表收集百分之10，如果不配置，有个默认的百分比的
  sleuth:
    sampler:
      probability: 0.3

# feign自身包含了hystrix，但是D版之后就是默认关闭的，true开启它
feign:
  hystrix:
    enabled: true


