# 服务名称
spring:
  application:
    name: springcloud_feign

# 指定端口
server:
  port: 8884

# feign负载均衡器作为一个服务消费者，允许被注册
# 指向server:服务发现者（8880），形成映射关系
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8880/eureka/

# feign自身包含了hystrix，但是D版之后就是默认关闭的，true开启它
feign:
  hystrix:
    enabled: true

