# 服务名称
spring:
  application:
    name: springcloud_eureka_server
  # 字符集
  banner:
    charset: UTF-8
  messages:
    encoding: UTF-8
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  # 数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/springboot_project?characterEncoding=UTF-8
    username: root
    password: 981214
    driverClassName: com.mysql.jdbc.Driver
  # Jpa配置.
  jpa:
    # 指定数据库
    database: mysql
    # 是否显示每个SQL查询的日志
    show-sql: true
    hibernate:
      # Hibernate DDL自动（创建、创建、删除、更新、验证、无）
      ddl-auto: update
      # 命名策略org.hibernate.cfg.ImprovedNamingStrategy和org.hibernate.cfg.DefaultNamingStrategy
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        # 在将它们添加到实体管理器之前将其剥离
        dialect: org.hibernate.dialect.MySQL5Dialect
        hbm2ddl:
          auto: update
# log配置.
logging:
  path: ../springcloud_project/log
  level:
    com:
      favorites: DEBUG
    org:
      springframework:
        web: INFO
      hibernate: ERROR

# 指定端口
server:
  port: 8880

# eureka会将自己作为client来尝试注册
# 这个服务是作为server而不是client，我们需要禁止它注册自身
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/


