# 服务名称
spring:
  application:
    name: springcloud_zuul

# 指定端口
server:
  port: 8885

# zuulAPI网关作为一个服务消费者，允许被注册
# 指向server:服务发现者（8880），形成映射关系
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8880/eureka/

# 以/api-ribbon/开头的请求都转发给springcloud-ribbon服务，例如访问localhost:8885/api-ribbon/hellWorld
# 以/api-feign/开头的请求都转发给springcloud-feign服务，例如访问localhost:8885/api-feign/hellWorld
# **可以匹配多个服务,*仅仅只能匹配单个服务
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: springcloud-ribbon
    api-b:
      path: /api-b/**
      serviceId: springcloud-feign
