# 指定端口
server:
  port: 8887
  tomcat:
    uri-encoding: UTF-8

# 服务名称
spring:
  application:
    name: springcloud_config_client
  cloud:
    config:
      # 文件前缀名
      name: springcloud
      # 指明远程仓库的分支
      label: master
      # 需要读取的配置文件名
      profile: demo
      # 指明配置服务中心的网址
      uri: http://localhost:8888/
