# 指定端口（config配置中心的端口必须为8888，需要改变要在bootstrap.yml里面指定端口）
server:
  port: 8888
  tomcat:
    uri-encoding: UTF-8

# spring-cloud配置
spring:
  application:
    # 服务名称
    name: springcloud-config-server

  # 配置到远程git仓库
  # config读取git远程仓库的配置文件，访问形式
  # 127.0.0.1:8887/文件名/随便取个名字
  # /{application}/{profile}[/{label}]
  # /{application}-{profile}.yml
  # /{label}/{application}-{profile}.yml
  # /{application}-{profile}.properties
  # /{label}/{application}-{profile}.properties
  cloud:
    config:
      server:
        git:
          # 配置git仓库地址
          uri: https://github.com/SoulMate1214/springcloud_config
          # 配置仓库路径
          searchPaths: src
          # 访问git仓库的用户名（如果是公开的，不需要用户名和密码）
          username:
          # 访问git仓库的用户密码
          password:
      # 配置仓库的分支
      label: master

