# 指定端口
server:
  port: 8883

# spring-cloud配置
spring:
  application:
    # 服务名称
    name: springcloud-ribbon

#开启熔断监控
management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"

